server:
  port: 8080
spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:hsqldb:hsql:/localhost:9001/db
    driverClassName: org.hsqldb.jdbcDriver
    username: root
    password: pass
  jpa:
    show-sql: true
    open-in-view: false
  application:
    payment:
      apiKey: sandbox-Hx6DvxaWsTe8KkX9IixOCLhdye4YrzoA
      apiSecretKey: sandbox-SxBzSskY6zIg038BcqoUNzUxyVL1FnFU
      apiUrl: https://sandbox-api.iyzipay.com
    itemsInSinglePage: 10